---
abstract: 'RT-Authen-OAuth2 Extension'
author:
  - 'Best Practical Solutions, LLC <modules@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: gpl_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Authen-OAuth2
no_index:
  directory:
    - etc
    - html
    - inc
    - static
requires:
  Net::OAuth2: 0
  perl: 5.10.1
resources:
  license: http://opensource.org/licenses/gpl-license.php
  repository: https://github.com/bestpractical/rt-authen-oauth2
version: '0.11'
x_module_install_rtx_version: '0.40'
x_requires_rt: 4.4.0
